development:
  adapter: mysql2
  encoding: utf8
  database: flatroad
  host: localhost
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: flatroad_test
  host: localhost
  username: root
  password:

production: